test site:
  image: node:11
  stage: test
  script:
    - npm install --progress=false
    - npm run test:unit
  artifacts:
    expire_in: 1 week
    paths:
      - dist

#unit test:
#  image: node:6
#  stage: test
#  script:
#    - npm install --progress=false
#    - npm run unit

deploy:
  stage: deploy
  script:
    - curl --request GET " https://forge.laravel.com/servers/315791/sites/847392/deploy/http?token=yj4fwkZh1MbpgrBZsNeU8WMrjJnvH6S8Kt4oahGi"
