build site:
  image: node:6
  stage: build
  script:
    - npm install --progress=false
    - npm run build:sit
  artifacts:
    expire_in: 1 week
    paths:
      - dist

#unit test:
#  image: node:6
#  stage: test
#  script:
#    - npm install --progress=false
#    - npm run unit

deploy:
  stage: deploy
  script:
    - curl --request GET "https://forge.laravel.com/servers/222171/sites/652441/deploy/http?token=703GMBDLBa4bCi5FgLRrjlr8QLfi1ylWxOhmuPfq"
